### ISSUE TITLE
help about LocalPlayerPointer

### ISSUE THREAD

**Issue by tony0305a** [Kuhicop/Tibia-OpenGL-Imgui#1]
hello, can you explain how do i get the LocalPlayerPointer? Thank you.

**Comment by Kuhicop** [comment]
hello, trace the mana up function, everytime the mana is going up, it will point to the pointer [localplayer_address + mana_offset]

get more information here:
https://www.youtube.com/watch?v=KjOozynV1lY
https://www.youtube.com/watch?v=YaFlh2pIKAg

you can also read my step by step introduction to game hacking:
https://github.com/Kuhicop/Game-Hacking

what you need it's to understand the basics then you can start playing from there

**Comment by tony0305a** [comment]
thank you again. you're awsome.

**Comment by Kuhicop** [comment]
> thank you again. you're awsome.

check the channel "cheat the game" I think it's already in my introduction but he has a very unique way to explain things, he can show you advanced aspects of Cheat Engine which is a tool valid for almost every game hacking purpose

at the end the idea behind game programming is general so you can apply a lot of concepts from one game to another, at entry level it's just interesting values at X memory locations and if you're not dealing with a driver level anticheat you have full control of everything :)

cheers
